apiVersion: v1
kind: Secret
metadata:
  name: camframe-analyzer
  namespace: crowd-analytics
data:
  AzureWebJobsStorage: #{funcStorage}#
  FUNCTIONS_WORKER_RUNTIME: #{funcRuntime}#
  APPINSIGHTS_INSTRUMENTATIONKEY: #{appInsightsKey}#
  serviceBusConnection: #{serviceBusConnection}#
  KEDA_SERVICE_BUS_CONNECTION: #{kedaServiceBusConnection}#
  camFrameStorageConnection: #{camFrameStorageConnection}#
  cognitiveKey: #{cognitiveKey}#
  cognitiveEndpoint: #{cognitiveEndpoint}#
  cosmosDbEndpoint: #{cosmosDbEndpoint}#
  cosmosDbKey: #{cosmosDbKey}#
  faceWorkspaceDataFilter: #{faceWorkspaceDataFilter}#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camframe-analyzer
  namespace: crowd-analytics
  labels:
    app: camframe-analyzer
spec:
  selector:
    matchLabels:
      app: camframe-analyzer
  template:
    metadata:
      labels:
        app: camframe-analyzer
    spec:
      containers:
      - name: camframe-analyzer
        image: #{acrName}#/crowdanalytics/camframe-analyzer:#{Build.BuildId}#
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: CamFrameAnalyzer
        envFrom:
        - secretRef:
            name: camframe-analyzer
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: camframe-analyzer
  namespace: crowd-analytics
  labels:
    deploymentName: camframe-analyzer
spec:
  scaleTargetRef:
    deploymentName: camframe-analyzer
  pollingInterval: 30  # Optional. Default: 30 seconds
  cooldownPeriod:  300 # Optional. Default: 300 seconds
  minReplicaCount: 0   # Optional. Default: 0
  maxReplicaCount: 100 # Optional. Default: 100
  triggers:
  - type: azure-servicebus
    metadata:
      type: serviceBusTrigger
      connection: KEDA_SERVICE_BUS_CONNECTION
      topicName: camframe-analysis
      subscriptionName: camframe-analyzer
      name: request
---

