apiVersion: v1
kind: Secret
metadata:
  name: crowd-analyzer
  namespace: crowd-analytics
data:
  AzureWebJobsStorage: #{funcStorage}#
  FUNCTIONS_WORKER_RUNTIME: ZG90bmV0 # dotnet
  APPINSIGHTS_INSTRUMENTATIONKEY: #{appInsightsKey}#
  serviceBusConnection: #{serviceBusConnection}#
  KEDA_SERVICE_BUS_CONNECTION: #{kedaServiceBusConnection}#
  origin: Q3Jvd2REZW1vZ3JhcGhpY3MuVjEuMC4w # CrowdDemographics.V1.0.0
  checkForDbConsistency: dHJ1ZQ== #true
  cosmosDbEndpoint: #{cosmosDbEndpoint}#
  cosmosDbKey: #{cosmosDbKey}#
  faceWorkspaceDataFilter: Q29udG9zby5Dcm93ZEFuYWx5dGljcw== # Contoso.CrowdAnalytics
  demographicsWindowMins: NjA= # 60
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crowd-analyzer
  namespace: crowd-analytics
  labels:
    app: crowd-analyzer
spec:
  selector:
    matchLabels:
      app: crowd-analyzer
  template:
    metadata:
      labels:
        app: crowd-analyzer
    spec:
      containers:
      - name: crowd-analyzer
        image: #{acrName}#/crowdanalytics/crowd-analyzer:#{Build.BuildId}#
        imagePullPolicy: IfNotPresent
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: CrowdAnalyzer
        envFrom:
        - secretRef:
            name: crowd-analyzer
      # If your AKS Virtual Nodes and ACR is configured correctly, you can schedule the scaling on virtual nodes
      # imagePullSecrets:
      # - name: acrImagePullSecret
      # nodeSelector:
      #   kubernetes.io/role: agent
      #   beta.kubernetes.io/os: linux
      #   type: virtual-kubelet
      # tolerations:
      # - key: virtual-kubelet.io/provider
      #   operator: Exists
      # - key: azure.com/aci
      #   effect: NoSchedule
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: crowd-analyzer
  namespace: crowd-analytics
  labels:
    deploymentName: crowd-analyzer
spec:
  scaleTargetRef:
    deploymentName: crowd-analyzer
  pollingInterval: 30  # Optional. Default: 30 seconds
  cooldownPeriod:  300 # Optional. Default: 300 seconds
  minReplicaCount: 0   # Optional. Default: 0
  maxReplicaCount: 100 # Optional. Default: 100
  triggers:
  - type: azure-servicebus
    metadata:
      connection: KEDA_SERVICE_BUS_CONNECTION
      topicName: crowd-analysis 
      subscriptionName: crowd-analyzer
      queueLength: '10' # This will be used to trigger a scale up operation when number of messages exceed this number
---

