apiVersion: v1
kind: Secret
metadata:
  name: crowd-analyzer
  namespace: crowd-analytics
data:
  AzureWebJobsStorage: #{funcStorage}#
  FUNCTIONS_WORKER_RUNTIME: ZG90bmV0 # dotnet
  APPINSIGHTS_INSTRUMENTATIONKEY: #{appInsightsKey}#
  serviceBusConnection: #{serviceBusConnection}#
  KEDA_SERVICE_BUS_CONNECTION: #{kedaServiceBusConnection}#
  origin: Q3Jvd2REZW1vZ3JhcGhpY3MuVjEuMC4w # CrowdDemographics.V1.0.0
  checkForDbConsistency: dHJ1ZQ== #true
  cosmosDbEndpoint: #{cosmosDbEndpoint}#
  cosmosDbKey: #{cosmosDbKey}#
  faceWorkspaceDataFilter: Q29udG9zby5Dcm93ZEFuYWx5dGljcw== # Contoso.CrowdAnalytics
  demographicsWindowMins: NjA= # 60
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crowd-analyzer
  namespace: crowd-analytics
  labels:
    app: crowd-analyzer
spec:
  selector:
    matchLabels:
      app: crowd-analyzer
  template:
    metadata:
      labels:
        app: crowd-analyzer
    spec:
      containers:
      - name: crowd-analyzer
        image: #{acrName}#/crowdanalytics/crowd-analyzer:#{Build.BuildId}#
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: CrowdAnalyzer
        - name: KEDA_SERVICE_BUS_CONNECTION
          valueFrom:
            secretKeyRef:
              name: crowd-analyzer
              key: KEDA_SERVICE_BUS_CONNECTION
        envFrom:
        - secretRef:
            name: crowd-analyzer
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: crowd-analyzer
  namespace: crowd-analytics
  labels:
    deploymentName: crowd-analyzer
spec:
  scaleTargetRef:
    deploymentName: crowd-analyzer
  pollingInterval: 30  # Optional. Default: 30 seconds
  cooldownPeriod:  300 # Optional. Default: 300 seconds
  minReplicaCount: 0   # Optional. Default: 0
  maxReplicaCount: 100 # Optional. Default: 100
  triggers:
  - type: azure-servicebus
    metadata:
      type: serviceBusTrigger
      connection: KEDA_SERVICE_BUS_CONNECTION
      topicName: crowd-analysis 
      subscriptionName: crowd-analyzer
      name: request
---

